- name: Docker のドキュメント
  href: index.md
- name: クイック スタート
  expanded: true
  items:
    - name: Docker を使用した Ubuntu VM のデプロイ
      href: 'https://azure.microsoft.com/resources/templates/docker-simple-on-ubuntu/'
- name: チュートリアル
  items:
    - name: Docker と PostgreSQL を使用した Python Web アプリ
      href: ../app-service/containers/tutorial-python-postgresql-app.md?toc=%2fazure%2fpostgresql%2ftoc.json
    - name: Docker、Jenkins、Linux を使用した CI/CD
      href: /azure/jenkins/tutorial-jenkins-github-docker-cicd
- name: 操作方法ガイド
  items:
    - name: Docker VM 拡張機能
      href: /azure/virtual-machines/linux/dockerextension
    - name: Docker マシン
      href: /azure/virtual-machines/linux/docker-machine
    - name: Docker コンテナー レジストリ
      href: /azure/container-registry/container-registry-get-started-portal
- name: リソース
  items:
    - name: Azure のロードマップ
      href: 'https://azure.microsoft.com/roadmap/'
    - name: Docker の Azure ドライバー
      href: 'https://docs.docker.com/machine/drivers/azure/'
    - name: Docker for Azure サイト
      href: 'https://www.docker.com/docker-azure'
    - name: Docker サイト
      href: 'https://docker.com'