items:
- name: Azure 上の Ansible のドキュメント
  href: ./index.yml
- name: 概要
  items:
  - name: Azure 上の Ansible について
    href: ./ansible-overview.md
- name: クイック スタート
  items:
  - name: Linux VM での Ansible のインストール
    href: /azure/virtual-machines/linux/ansible-install-configure
    maintainContext: true
  - name: Linux VM の作成
    href: /azure/virtual-machines/linux/ansible-create-vm
    maintainContext: true
  - name: Linux VM の管理
    href: /azure/virtual-machines/linux/ansible-manage-linux-vm
    maintainContext: true
  expanded: true
- name: チュートリアル
  items:
  - name: Cloud Shell でのプレイブックの実行
    href: ./ansible-run-playbook-in-cloudshell.md
    maintainContext: true
  - name: 動的なインベントリの管理
    href: ./ansible-manage-azure-dynamic-inventories.md
    maintainContext: true
  - name: VMSS の作成と構成
    href: ./ansible-create-configure-vmss.md
  - name: VMSS へのアプリのデプロイ
    href: ./ansible-deploy-app-vmss.md
  - name: VMSS の自動スケーリング
    href: ./ansible-auto-scale-vmss.md
  - name: AKS クラスターの作成と構成
    href: ./ansible-create-configure-aks.md
  - name: Azure Application Gateway の作成と構成
    href: ./ansible-create-configure-application-gateway.md
  - name: Azure DB for MySQL の作成と構成
    href: ./ansible-create-configure-mysql.md
  - name: Azure Web Apps の作成と構成
    href: ./ansible-create-configure-azure-web-apps.md
  - name: Azure Web Apps のスケール
    href: ./ansible-scale-azure-web-apps.md
- name: リファレンス
  items:
  - name: プレイブックの役割
    items:
    - name: azure_module
      href: https://galaxy.ansible.com/Azure/azure_modules/
    - name: azure_preview_module
      href: https://galaxy.ansible.com/Azure/azure_preview_modules
  - name: リリースと機能
    href: ./ansible-matrix.md
  - name: Azure Container Instances
    href: https://docs.ansible.com/ansible/latest/azure_rm_containerinstance_module.html
  - name: Azure Functions
    href: https://docs.ansible.com/ansible/latest/azure_rm_functionapp_module.html
  - name: ロード バランサー
    href: https://docs.ansible.com/ansible/latest/azure_rm_loadbalancer_module.html
  - name: 仮想マシン
    href: https://docs.ansible.com/ansible/latest/azure_rm_virtualmachine_module.html
  - name: Azure 用のすべてのモジュール
    href: https://docs.ansible.com/ansible/latest/list_of_cloud_modules.html#azure
- name: ツール
  items:
  - name: Ansible 用 Visual Studio Code 拡張機能
    href: https://marketplace.visualstudio.com/items?itemName=vscoss.vscode-ansible
ms.openlocfilehash: f426841f2a02b085e34e9e2a768c43a052bf62f7
ms.sourcegitcommit: c37122644eab1cc739d735077cf971edb6d428fe
ms.translationtype: HT
ms.contentlocale: ja-JP
ms.lasthandoff: 12/14/2018
ms.locfileid: "53409141"
