- name: Kubernetes on Azure
  href: ./index.yml
- name: 概要
  items:
    - name: Kubernetes on Azure
      href: container-service-intro-kubernetes.md
- name: クイックスタート
  expanded: true
  items:
    - name: Kubernetes on Azure
      href: container-service-kubernetes-walkthrough.md
- name: チュートリアル
  items:
    - name: 1 - コンテナー イメージを作成する
      href: container-service-tutorial-kubernetes-prepare-app.md
    - name: 2 - コンテナー レジストリを作成する
      href: container-service-tutorial-kubernetes-prepare-acr.md
    - name: 3 - Kubernetes クラスターを作成する
      href: container-service-tutorial-kubernetes-deploy-cluster.md
    - name: 4 - アプリケーションを実行する
      href: container-service-tutorial-kubernetes-deploy-application.md
    - name: 5 - アプリケーションのスケールを変更する
      href: container-service-tutorial-kubernetes-scale.md
    - name: 6 - アプリケーションを更新する
      href: container-service-tutorial-kubernetes-app-update.md
    - name: 7 - Log Analytics を使用して監視する
      href: container-service-tutorial-kubernetes-monitor.md
- name: 概念
  items:
    - name: サービス プリンシパル - Kubernetes
      href: container-service-kubernetes-service-principal.md
- name: 操作方法ガイド
  items:
    - name: Windows と連携する Kubernetes
      href: container-service-kubernetes-windows-walkthrough.md
    - name: Kubernetes Web インターフェイス
      href: container-service-kubernetes-ui.md
    - name: Helm グラフの使用
      href: container-service-kubernetes-helm.md
    - name: Azure Files によるデータ保持
      href: ../../aks/azure-files.md?toc=%2fazure%2fcontainer-service%2fkubernetes%2ftoc.json
    - name: ACS での Draft の使用
      href: container-service-draft-up.md
    - name: クラスターのスケーリング
      href: container-service-scale.md
    - name: モニター
      items:
        - name: Log Analytics による監視
          href: container-service-kubernetes-oms.md
        - name: Datadog で監視する
          href: container-service-kubernetes-datadog.md
        - name: Sysdig で監視する
          href: container-service-kubernetes-sysdig.md
        - name: CoScale で監視する
          href: container-service-kubernetes-coscale.md
    - name: Spring Boot アプリのデプロイ
      items:
        - name: Azure Container Service で Spring Boot アプリケーションを Linux にデプロイする
          href: container-service-deploy-spring-boot-app-on-linux.md
        - name: Azure Container Service で Spring Boot アプリケーションを Kubernetes クラスターにデプロイする
          href: container-service-deploy-spring-boot-app-on-kubernetes.md
        - name: fabric8 Maven プラグインを使用して Spring Boot アプリをデプロイする
          href: container-service-deploy-spring-boot-app-using-fabric8-maven-plugin.md
- name: リファレンス
  items:
    - name: Azure CLI
      href: /cli/azure/acs
    - name: PowerShell
      href: /powershell/module/az.compute
    - name: REST
      href: /rest/api/container-service
- name: リソース
  items:
    - name: Azure のロードマップ
      href: 'https://azure.microsoft.com/roadmap/'
    - name: よく寄せられる質問
      href: container-service-faq.md
    - name: テンプレート - ACS Engine
      href: 'https://github.com/Azure/acs-engine'
    - name: 価格
      href: 'https://azure.microsoft.com/pricing/details/container-service/'
    - name: 利用可能なリージョン
      href: 'https://azure.microsoft.com/regions/services/'
    - name: スタック オーバーフロー
      href: 'https://stackoverflow.com/questions/tagged/azure-container-service'
    - name: ビデオ
      href: 'https://azure.microsoft.com/resources/videos/index/?services=container-service&sort=newest'