### YamlMime:Landing
title: Azure Arc 対応 Kubernetes
summary: Azure Arc を使用して Kubernetes クラスターを管理する方法について説明します
metadata:
  title: Azure Arc 対応 Kubernetes
  description: Azure でオンプレミスのマシンを管理する方法について説明します
  author: shashankbarsin
  ms.service: azure-arc
  ms.topic: landing-page
  ms.date: 03/02/2021
  ms.author: shasb
  ms.openlocfilehash: fbad5cafb22960a56a4ba76e2dc331c399193ddc
  ms.sourcegitcommit: 56b0c7923d67f96da21653b4bb37d943c36a81d6
  ms.translationtype: HT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 04/06/2021
  ms.locfileid: "106443200"
landingContent:
- title: Azure Arc 対応 Kubernetes について
  linkLists:
  - linkListType: overview
    links:
    - text: Azure Arc 対応 Kubernetes とは
      url: overview.md
    - text: Azure Arc 検証プログラム
      url: validation-program.md
  - linkListType: concept
    links:
    - text: エージェントのアーキテクチャ
      url: conceptual-agent-architecture.md
    - text: 構成と GitOps
      url: conceptual-configurations.md
    - text: GitOps を使用した CI/CD ワークフロー
      url: conceptual-gitops-ci-cd.md
    - text: よく寄せられる質問
      url: faq.md
- title: 作業開始
  linkLists:
  - linkListType: quickstart
    links:
    - text: Azure Arc にクラスターを接続する
      url: quickstart-connect-cluster.md
- title: GitOps を使用して構成をデプロイする
  linkLists:
  - linkListType: tutorial
    links:
    - text: GitOps を使用して構成をデプロイする
      url: tutorial-use-gitops-connected-cluster.md
    - text: GitOps を使用して CI/CD を実装する
      url: tutorial-gitops-ci-cd.md
- title: クラスタの構成、管理、監視
  linkLists:
  - linkListType: how-to-guide
    links:
    - text: GitOps を使用して Helm グラフをデプロイする
      url: use-gitops-with-helm.md
    - text: Azure Policy を使用して GitOps を適用する
      url: use-azure-policy.md
    - text: クラスターに拡張機能をデプロイする
      url: extensions.md
    - text: Azure IoT Edge ワークロードをデプロイする
      url: deploy-azure-iot-edge-workloads.md
- title: 概念実証
  linkLists:
  - linkListType: sample
    links:
    - text: ジャンプスタート
      url: https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_k8s/
- title: 参照アーキテクチャ
  linkLists:
  - linkListType: architecture
    links:
    - text: ハイブリッド Kubernetes クラスターのデプロイと構成を管理する
      url: /azure/architecture/hybrid/arc-hybrid-kubernetes
