- name: Azure Arc 対応 Kubernetes
  href: index.yml
- name: 概要
  items:
    - name: Azure Arc 対応 Kubernetes について
      href: overview.md
- name: 操作方法ガイド
  items:
    - name: クラスターの操作
      items:
        - name: クラスターの接続
          href: connect-cluster.md
        - name: 接続されたクラスターに GitOps を使用する
          href: use-gitops-connected-cluster.md
        - name: Helm で GitOps を使用する
          href: use-gitops-with-helm.md
        - name: コンテナーに対する Azure Monitor
          href: deploy-azure-monitor-for-containers.md
        - name: Azure Policy アドオンをインストールする
          href: ../../governance/policy/concepts/policy-for-kubernetes.md?toc=/azure/azure-arc/kubernetes/toc.json
        - name: Azure Policy を使用する
          href: use-azure-policy.md
        - name: IoT ワークロードをデプロイする
          href: deploy-azure-iot-edge-workloads.md
        - name: サービス プリンシパルのオンボード
          href: create-onboarding-service-principal.md
        - name: トラブルシューティング
          href: Troubleshooting.md